import { Action } from '@ngrx/store';

export const UPDATE_COUNTRIES_SELECTION = 'UPDATE_COUNTRIES_SELECTION';

export const UPDATE_ATTRIBUTES_SELECTION = 'UPDATE_ATTRIBUTES_SELECTION';

export const UPDATE_COLOR_MAP = 'UPDATE_COLOR_MAP';

