import { Action } from '@ngrx/store';

export const UPDATE_COUNTRIES_SELECTION = 'UPDATE_COUNTRIES_SELECTION';

export const UPDATE_ATTRIBUTES_SELECTION = 'UPDATE_ATTRIBUTES_SELECTION';

export const UPDATE_COLOR_MAP = 'UPDATE_COLOR_MAP';

export const DATA_TRANSFORMS_COMPLETE = 'DATA_TRANSFORMS_COMPLETE';

export const UPDATE_ATTRIBUTE_SET_FOR_COUNTRY = 'UPDATE_ATTRIBUTE_SET_FOR_COUNTRY';

